from backend.repository import WorkoutRepository


class WorkoutService:
    def __init__(self, repo: WorkoutRepository):
        self._repo = repo

    def search_exercises(self, q: str, equipment: list[str], muscle: list[str], level: list[str]) -> list[dict]:
        # Delegates to a Postgres RPC that JOINs exercises with muscle_groups server-side
        return self._repo.search_exercises(q=q, equipment=equipment, muscle=muscle, level=level)

    def log_workout(self, uid: str, name: str | None, date: str, duration_seconds: int, exercises: list[dict]) -> dict:
        # Persists the finished session. workout_id is generated by Postgres on the workouts insert
        # and returned here so Flutter can reference this session (e.g. for a summary screen)
        workout_id = self._repo.log_workout(
            uid=uid,
            name=name,
            date=date,
            duration_seconds=duration_seconds,
            exercises=exercises,
        )
        return {"workout_id": workout_id}

    def get_recent_workouts(self, uid: str) -> list[dict]:
        # Returns the 10 most recently completed sessions, ordered by created_at so two
        # sessions on the same date are still returned in the correct order
        return self._repo.get_recent_workouts(uid)
