from backend.repository import WorkoutRepository


class WorkoutService:
    def __init__(self, repo: WorkoutRepository):
        self._repo = repo

    def search_exercises(self, uid: str, q: str, equipment: list[str], muscle: list[str], level: list[str]) -> list[dict]:
        # Delegates to a Postgres RPC that JOINs exercises with muscle_groups server-side
        return self._repo.search_exercises(uid=uid, q=q, equipment=equipment, muscle=muscle, level=level)

    def create_custom_exercise(self, uid: str, name: str, primary_muscle: str | None, secondary_muscles: list[str], equipment: str | None, level: str | None) -> dict:
        return self._repo.create_custom_exercise(uid=uid, name=name, primary_muscle=primary_muscle, secondary_muscles=secondary_muscles, equipment=equipment, level=level)

    def edit_custom_exercise(self, uid: str, exercise_id: int, name: str, primary_muscle: str | None, secondary_muscles: list[str], equipment: str | None, level: str | None) -> None:
        self._repo.edit_custom_exercise(uid=uid, exercise_id=exercise_id, name=name, primary_muscle=primary_muscle, secondary_muscles=secondary_muscles, equipment=equipment, level=level)

    def delete_custom_exercise(self, uid: str, exercise_id: int) -> None:
        self._repo.delete_custom_exercise(uid=uid, exercise_id=exercise_id)

    def log_workout(self, uid: str, name: str | None, date: str, duration_seconds: int, exercises: list[dict]) -> dict:
        # Persists the finished session. workout_id is generated by Postgres on the workouts insert
        # and returned here so Flutter can reference this session (e.g. for a summary screen)

        # server-side guard: drop any sets where both reps and weight are zero or missing,
        # then drop exercises that have no valid sets left after that filter
        clean_exercises = []
        for ex in exercises:
            valid_sets = [s for s in ex["sets"] if (s.get("reps") or 0) > 0 or (s.get("weight_kg") or 0) > 0]
            if valid_sets:
                clean_exercises.append({**ex, "sets": valid_sets})

        if not clean_exercises:
            raise ValueError("No valid sets to log")  # caught in the route and returned as 400

        workout_id = self._repo.log_workout(
            uid=uid,
            name=name,
            date=date,
            duration_seconds=duration_seconds,
            exercises=clean_exercises,
        )
        return {"workout_id": workout_id}

    def get_recent_workouts(self, uid: str) -> list[dict]:
        # Returns the 10 most recently completed sessions, ordered by created_at so two
        # sessions on the same date are still returned in the correct order
        return self._repo.get_recent_workouts(uid)

    def get_recent_exercises(self, uid: str) -> list[dict]:
        # Returns the most recently used unique exercises across all of the user's sessions
        return self._repo.get_recent_exercises(uid)

    def get_workout_heatmap(self, uid: str) -> list[dict]:
        return self._repo.get_workout_heatmap(uid)

    def get_today_overview(self, uid: str) -> dict:
        return self._repo.get_today_overview(uid)

    def get_weekly_workout_count(self, uid: str) -> int:
        # Returns the number of completed workouts since the most recent Monday
        return self._repo.get_weekly_workout_count(uid)
