import 'package:flutter/material.dart';

// Returns a Material icon based on the POI category string
class POIIcons {
  static const Map<String, IconData> _categoryIcons = {
    'restaurant': Icons.restaurant,
    'fast_food': Icons.restaurant,
    'cafe': Icons.restaurant,
    'bar': Icons.restaurant,
    'pub': Icons.restaurant,
    'deli': Icons.restaurant,
    'fitness_centre': Icons.fitness_center,
    'sports_centre': Icons.fitness_center,
    'gym': Icons.fitness_center,
    'park': Icons.park,
    'garden': Icons.park,
    'playground': Icons.park,
    'supermarket': Icons.shopping_cart,
    'convenience': Icons.shopping_cart,
    'bakery': Icons.shopping_cart,
    'greengrocer': Icons.shopping_cart,
    'pharmacy': Icons.medication_liquid,
    'chemist': Icons.medication_liquid,
    'hospital': Icons.local_hospital,
    'bus_service': Icons.directions_bus,
    'swimming_pool': Icons.pool,
    'beaty': Icons.brush,
    'clinic': Icons.medication_liquid,
    'doctors': Icons.medication_liquid,
    'dentist': Icons.medication_liquid,
    'optician': Icons.medication_liquid,
    'school': Icons.school,
    'university': Icons.school,
    'college': Icons.school,
    'library': Icons.library_books,
    'driving_school': Icons.school,
    'video_games': Icons.videogame_asset,
    'hairdresser': Icons.cut,
    'hotel': Icons.hotel,
    'hostel': Icons.hotel,
    'guest_house': Icons.hotel,
    'museum': Icons.museum,
    'gallery': Icons.museum,
    'theatre': Icons.museum,
    'cinema': Icons.museum,
    'weapons': Icons.dangerous_outlined,
    'musical_instrument': Icons.music_note,
    'taxi': Icons.local_taxi,
    'police': Icons.local_police,
    'parking': Icons.local_parking,
    'bank': Icons.attach_money_outlined,
    'atm': Icons.attach_money_outlined,
    'fuel': Icons.local_gas_station,
    'gift': Icons.card_giftcard,
    'toilets': Icons.wc_rounded,
    'artwork': Icons.brush,
    'books': Icons.book,
    'recycling': Icons.recycling,
    'information': Icons.info_rounded,
    'ice_cream': Icons.icecream,
    'car_repair': Icons.car_repair,
    'dry_cleaning': Icons.dry_cleaning,
    'post_office': Icons.local_post_office,
    'post_box': Icons.local_post_office,
    'laundry': Icons.local_laundry_service,
  };

  static IconData fromCategory(String category) {
    return _categoryIcons[category] ??
        Icons.place; // generic pin for everything else
  }
}
