import 'package:flutter/material.dart';
import 'package:hugeicons/hugeicons.dart';

// Returns a HugeIcon based on the POI category string
class POIIcons {
  static const Map<String, IconData> _categoryIcons = {
    'restaurant': HugeIcons.strokeRoundedRestaurant01,
    'fast_food': HugeIcons.strokeRoundedHamburger02,
    'cafe': HugeIcons.strokeRoundedCoffee01,
    'bar': HugeIcons.strokeRoundedDrink,
    'pub': HugeIcons.strokeRoundedDrink,
    'deli': HugeIcons.strokeRoundedRestaurant01,
    'fitness_centre': HugeIcons.strokeRoundedDumbbell01,
    'sports_centre': HugeIcons.strokeRoundedActivity01,
    'gym': HugeIcons.strokeRoundedDumbbell01,
    'park': HugeIcons.strokeRoundedTree01,
    'garden': HugeIcons.strokeRoundedFlower,
    'playground': HugeIcons.strokeRoundedSlide,
    'supermarket': HugeIcons.strokeRoundedShoppingCart01,
    'convenience': HugeIcons.strokeRoundedShoppingBag01,
    'bakery': HugeIcons.strokeRoundedBread01,
    'greengrocer': HugeIcons.strokeRoundedVegetarianFood,
    'pharmacy': HugeIcons.strokeRoundedMedicine01,
    'chemist': HugeIcons.strokeRoundedMedicine01,
    'hospital': HugeIcons.strokeRoundedHospital01,
    'bus_service': HugeIcons.strokeRoundedBus01,
    'swimming_pool': HugeIcons.strokeRoundedSwimming,
    'beauty': HugeIcons.strokeRoundedBlushBrush02,
    'clinic': HugeIcons.strokeRoundedClinic,
    'doctors': HugeIcons.strokeRoundedDoctor01,
    'dentist': HugeIcons.strokeRoundedDentalTooth,
    'optician': HugeIcons.strokeRoundedGlasses,
    'school': HugeIcons.strokeRoundedSchool01,
    'university': HugeIcons.strokeRoundedUniversity,
    'college': HugeIcons.strokeRoundedUniversity,
    'library': HugeIcons.strokeRoundedLibrary,
    'driving_school': HugeIcons.strokeRoundedCar01,
    'video_games': HugeIcons.strokeRoundedGameController01,
    'hairdresser': HugeIcons.strokeRoundedHairDryer,
    'hotel': HugeIcons.strokeRoundedHotel01,
    'hostel': HugeIcons.strokeRoundedHotel01,
    'guest_house': HugeIcons.strokeRoundedHotel01,
    'museum': HugeIcons.strokeRoundedBank,
    'gallery': HugeIcons.strokeRoundedArtboard,
    'theatre': HugeIcons.strokeRoundedMaskTheater01,
    'cinema': HugeIcons.strokeRoundedCameraVideo,
    'musical_instrument': HugeIcons.strokeRoundedMusicNote01,
    'taxi': HugeIcons.strokeRoundedTaxi,
    'police': HugeIcons.strokeRoundedPoliceBadge,
    'parking': HugeIcons.strokeRoundedParkingAreaSquare,
    'bank': HugeIcons.strokeRoundedBank,
    'atm': HugeIcons.strokeRoundedCreditCard,
    'fuel': HugeIcons.strokeRoundedPetrolPump,
    'gift': HugeIcons.strokeRoundedGift,
    'toilets': HugeIcons.strokeRoundedToilet01,
    'artwork': HugeIcons.strokeRoundedPaintBoard,
    'books': HugeIcons.strokeRoundedBook01,
    'recycling': HugeIcons.strokeRoundedRecycle03,
    'information': HugeIcons.strokeRoundedInformationCircle,
    'ice_cream': HugeIcons.strokeRoundedIceCream01,
    'car_repair': HugeIcons.strokeRoundedWrench01,
    'dry_cleaning': HugeIcons.strokeRoundedHanger,
    'post_office': HugeIcons.strokeRoundedMailbox01,
    'post_box': HugeIcons.strokeRoundedMailbox01,
    'laundry': HugeIcons.strokeRoundedUnderpants01,
    'weapons': HugeIcons.strokeRoundedKnife01,
  };

  static IconData fromCategory(String category) {
    return _categoryIcons[category] ??
        HugeIcons.strokeRoundedLocation01; // generic pin for everything else
  }
}
